package Presentacion.Controller;

public enum Eventos {
	
	// GUI
	MOSTRAR_INICIO,
	MOSTRAR_TIENDA,
	MOSTRAR_MUSEO,
	
	// FABRICANTE
	REGISTRAR_FABRICANTE, REGISTRAR_FABRICANTE_OK, REGISTRAR_FABRICANTE_KO,
	MODIFICAR_FABRICANTE, MODIFICAR_FABRICANTE_OK, MODIFICAR_FABRICANTE_KO,
	BORRAR_FABRICANTE, BORRAR_FABRICANTE_OK, BORRAR_FABRICANTE_KO,
	MOSTRAR_LISTA_FABRICANTES, MOSTRAR_LISTA_FABRICANTES_OK, MOSTRAR_LISTA_FABRICANTES_KO,
	BUSCAR_FABRICANTE_POR_ID, BUSCAR_FABRICANTE_POR_ID_OK, BUSCAR_FABRICANTE_POR_ID_KO,
	
	// CLIENTE
	REGISTRAR_CLIENTE, REGISTRAR_CLIENTE_OK, REGISTRAR_CLIENTE_KO,
	MODIFICAR_CLIENTE, MODIFICAR_CLIENTE_OK, MODIFICAR_CLIENTE_KO,
	BORRAR_CLIENTE, BORRAR_CLIENTE_OK, BORRAR_CLIENTE_KO,
	MOSTRAR_LISTA_CLIENTES, MOSTRAR_LISTA_CLIENTES_OK, MOSTRAR_LISTA_CLIENTES_KO,
	BUSCAR_CLIENTE_POR_ID, BUSCAR_CLIENTE_POR_ID_OK, BUSCAR_CLIENTE_POR_ID_KO,
	LISTAR_CLIENTES_POR_TIPO, LISTAR_CLIENTES_POR_TIPO_OK, LISTAR_CLIENTES_POR_TIPO_KO,
	
	// DESCUENTO
	REGISTRAR_DESCUENTO, REGISTRAR_DESCUENTO_OK, REGISTRAR_DESCUENTO_KO,
	MODIFICAR_DESCUENTO, MODIFICAR_DESCUENTO_OK, MODIFICAR_DESCUENTO_KO,
	BORRAR_DESCUENTO, BORRAR_DESCUENTO_OK, BORRAR_DESCUENTO_KO,
	MOSTRAR_LISTA_DESCUENTO, MOSTRAR_LISTA_DESCUENTO_OK, MOSTRAR_LISTA_DESCUENTO_KO,
	BUSCAR_DESCUENTO_POR_ID, BUSCAR_DESCUENTO_POR_ID_OK, BUSCAR_DESCUENTO_POR_ID_KO,
	
	// PRODUCTO
	REGISTRAR_PRODUCTO, REGISTRAR_PRODUCTO_OK, REGISTRAR_PRODUCTO_KO,
	MODIFICAR_PRODUCTO, MODIFICAR_PRODUCTO_OK, MODIFICAR_PRODUCTO_KO,
	BORRAR_PRODUCTO, BORRAR_PRODUCTO_OK, BORRAR_PRODUCTO_KO,
	MOSTRAR_LISTA_PRODUCTOS, MOSTRAR_LISTA_PRODUCTOS_OK, MOSTRAR_LISTA_PRODUCTOS_KO,
	BUSCAR_PRODUCTO_POR_ID, BUSCAR_PRODUCTO_POR_ID_OK, BUSCAR_PRODUCTO_POR_ID_KO,
	LEER_POR_ID_FABRICANTE, LEER_POR_ID_FABRICANTE_OK, LEER_POR_ID_FABRICANTE_KO,
	MOSTRAR_PRODUCTO_POR_NOMBRE_FABRICANTE, MOSTRAR_PRODUCTO_POR_NOMBRE_FABRICANTE_OK, MOSTRAR_PRODUCTO_POR_NOMBRE_FABRICANTE_KO,
	
	// FACTURA TIENDA
	ABRIR_FACTURA,
	AÑADIR_PRODUCTO, AÑADIR_PRODUCTO_OK, AÑADIR_PRODUCTO_KO,
	BUSCAR_FACTURA_POR_ID, BUSCAR_FACTURA_POR_ID_OK, BUSCAR_FACTURA_POR_ID_KO,
	CERRAR_FACTURA, CERRAR_FACTURA_OK, CERRAR_FACTURA_KO,
	DEVOLVER_PRODUCTO, DEVOLVER_PRODUCTO_OK, DEVOLVER_PRODUCTO_KO,
	MOSTRAR_LISTA_FACTURAS, MOSTRAR_LISTA_FACTURAS_OK, MOSTRAR_LISTA_FACTURAS_KO,
	QUITAR_PRODUCTO, QUITAR_PRODUCTO_OK, QUITAR_PRODUCTO_KO,
	LEER_POR_ID_CLIENTE, LEER_POR_ID_CLIENTE_OK, LEER_POR_ID_CLIENTE_KO,
	LEER_POR_ID_DESCUENTO, LEER_POR_ID_DESCUENTO_OK, LEER_POR_ID_DESCUENTO_KO,
	MOSTRAR_PRODUCTO_MAS_COMPRADO, MOSTRAR_PRODUCTO_MAS_COMPRADO_OK, MOSTRAR_PRODUCTO_MAS_COMPRADO_KO,
	MOSTRAR_FACTURA_CON_MAYOR_PORCENTAJE_DESCUENTO, MOSTRAR_FACTURA_CON_MAYOR_PORCENTAJE_DESCUENTO_OK, MOSTRAR_FACTURA_CON_MAYOR_PORCENTAJE_DESCUENTO_KO,
	MOSTRAR_FACTURA_TIENDA_COMPLETA, MOSTRAR_FACTURA_TIENDA_COMPLETA_OK, MOSTRAR_FACTURA_TIENDA_COMPLETA_KO,
	
	// EMPLEADO
	REGISTRAR_EMPLEADO, REGISTRAR_EMPLEADO_OK, REGISTRAR_EMPLEADO_KO,
	MODIFICAR_EMPLEADO, MODIFICAR_EMPLEADO_OK, MODIFICAR_EMPLEADO_KO,
	BORRAR_EMPLEADO, BORRAR_EMPLEADO_OK, BORRAR_EMPLEADO_KO,
	MOSTRAR_LISTA_EMPLEADOS, MOSTRAR_LISTA_EMPLEADOS_OK, MOSTRAR_LISTA_EMPLEADOS_KO,
	BUSCAR_EMPLEADO_POR_ID, BUSCAR_EMPLEADO_POR_ID_OK, BUSCAR_EMPLEADO_POR_ID_KO,
	LISTAR_EMPLEADOS_POR_JORNADA, LISTAR_EMPLEADOS_POR_JORNADA_OK, LISTAR_EMPLEADOS_POR_JORNADA_KO,
	LEER_POR_ID_TURNO, LEER_POR_ID_TURNO_OK, LEER_POR_ID_TURNO_KO,
	MOSTRAR_NOMINA_EMPLEADO, MOSTRAR_NOMINA_EMPLEADO_OK, MOSTRAR_NOMINA_EMPLEADO_KO,
	
	// TURNO EMPLEADO
	REGISTRAR_TURNO, REGISTRAR_TURNO_OK, REGISTRAR_TURNO_KO,
	MODIFICAR_TURNO, MODIFICAR_TURNO_OK, MODIFICAR_TURNO_KO,
	BORRAR_TURNO, BORRAR_TURNO_OK, BORRAR_TURNO_KO,
	LISTAR_TURNOS, LISTAR_TURNOS_OK, LISTAR_TURNOS_KO,
	BUSCAR_TURNO_POR_ID, BUSCAR_TURNO_POR_ID_OK, BUSCAR_TURNO_POR_ID_KO,
	CALCULO_NOMINA_TURNO, CALCULO_NOMINA_TURNO_OK, CALCULO_NOMINA_TURNO_KO,
	
	//FACTURA MUSEO
	ABRIR_FACTURA_MUSEO,
	AÑADIR_ENTRADA, AÑADIR_ENTRADA_OK, AÑADIR_ENTRADA_KO,
	BUSCAR_FACTURA_MUSEO_POR_ID, BUSCAR_FACTURA_MUSEO_POR_ID_OK, BUSCAR_FACTURA_MUSEO_POR_ID_KO,
	DEVOLVER_ENTRADA, DEVOLVER_ENTRADA_OK, DEVOLVER_ENTRADA_KO,
	QUITAR_ENTRADA, QUITAR_ENTRADA_OK, QUITAR_ENTRADA_KO,
	MOSTRAR_LISTA_FACTURAS_MUSEO, MOSTRAR_LISTA_FACTURAS_MUSEO_OK, MOSTRAR_LISTA_FACTURAS_MUSEO_KO,
	CERRAR_FACTURA_MUSEO, CERRAR_FACTURA_MUSEO_OK, CERRAR_FACTURA_MUSEO_KO,
	LEER_POR_ID_EMPLEADO, LEER_POR_ID_EMPLEADO_OK, LEER_POR_ID_EMPLEADO_KO,
	MOSTRAR_FACTURA_COMPLETA, MOSTRAR_FACTURA_COMPLETA_OK, MOSTRAR_FACTURA_COMPLETA_KO,
	
	// ENTRADA
	REGISTRAR_ENTRADA, REGISTRAR_ENTRADA_OK, REGISTRAR_ENTRADA_KO,
	MODIFICAR_ENTRADA, MODIFICAR_ENTRADA_OK, MODIFICAR_ENTRADA_KO,
	BORRAR_ENTRADA, BORRAR_ENTRADA_OK, BORRAR_ENTRADA_KO,
	MOSTRAR_LISTA_ENTRADAS, MOSTRAR_LISTA_ENTRADAS_OK, MOSTRAR_LISTA_ENTRADAS_KO,
	BUSCAR_ENTRADA_POR_ID, BUSCAR_ENTRADA_POR_ID_OK, BUSCAR_ENTRADA_POR_ID_KO
}