package Presentacion.Controller;

public enum Eventos {
	
    // GUI
        MOSTRAR_INICIO,
    
    // FABRICANTE
    REGISTRAR_FABRICANTE, REGISTRAR_FABRICANTE_OK, REGISTRAR_FABRICANTE_KO,
    MODIFICAR_FABRICANTE, MODIFICAR_FABRICANTE_OK, MODIFICAR_FABRICANTE_KO,
    BORRAR_FABRICANTE, BORRAR_FABRICANTE_OK, BORRAR_FABRICANTE_KO,
    MOSTRAR_LISTA_FABRICANTES, MOSTRAR_LISTA_FABRICANTES_OK, MOSTRAR_LISTA_FABRICANTES_KO,
    BUSCAR_FABRICANTE_POR_ID, BUSCAR_FABRICANTE_POR_ID_OK, BUSCAR_FABRICANTE_POR_ID_KO,
    
    // CLIENTE
    REGISTRAR_CLIENTE, REGISTRAR_CLIENTE_OK, REGISTRAR_CLIENTE_KO,
    MODIFICAR_CLIENTE, MODIFICAR_CLIENTE_OK, MODIFICAR_CLIENTE_KO,
    BORRAR_CLIENTE, BORRAR_CLIENTE_OK, BORRAR_CLIENTE_KO,
    MOSTRAR_LISTA_CLIENTES, MOSTRAR_LISTA_CLIENTES_OK, MOSTRAR_LISTA_CLIENTES_KO,
    BUSCAR_CLIENTE_POR_ID, BUSCAR_CLIENTE_POR_ID_OK, BUSCAR_CLIENTE_POR_ID_KO,
    LISTAR_CLIENTES_POR_TIPO, LISTAR_CLIENTES_POR_TIPO_OK, LISTAR_CLIENTES_POR_TIPO_KO,
    
    // DESCUENTO
    REGISTRAR_DESCUENTO, REGISTRAR_DESCUENTO_OK, REGISTRAR_DESCUENTO_KO,
    MODIFICAR_DESCUENTO, MODIFICAR_DESCUENTO_OK, MODIFICAR_DESCUENTO_KO,
    BORRAR_DESCUENTO, BORRAR_DESCUENTO_OK, BORRAR_DESCUENTO_KO,
    MOSTRAR_LISTA_DESCUENTO, MOSTRAR_LISTA_DESCUENTO_OK, MOSTRAR_LISTA_DESCUENTO_KO,
    BUSCAR_DESCUENTO_POR_ID, BUSCAR_DESCUENTO_POR_ID_OK, BUSCAR_DESCUENTO_POR_ID_KO,
    
    // PRODUCTO
    REGISTRAR_PRODUCTO, REGISTRAR_PRODUCTO_OK, REGISTRAR_PRODUCTO_KO,
    MODIFICAR_PRODUCTO, MODIFICAR_PRODUCTO_OK, MODIFICAR_PRODUCTO_KO,
    BORRAR_PRODUCTO, BORRAR_PRODUCTO_OK, BORRAR_PRODUCTO_KO,
    MOSTRAR_LISTA_PRODUCTOS, MOSTRAR_LISTA_PRODUCTOS_OK, MOSTRAR_LISTA_PRODUCTOS_KO,
    BUSCAR_PRODUCTO_POR_ID, BUSCAR_PRODUCTO_POR_ID_OK, BUSCAR_PRODUCTO_POR_ID_KO,
    LEER_POR_ID_FABRICANTE, LEER_POR_ID_FABRICANTE_OK, LEER_POR_ID_FABRICANTE_KO,
    MOSTRAR_PRODUCTO_POR_NOMBRE_FABRICANTE, MOSTRAR_PRODUCTO_POR_NOMBRE_FABRICANTE_OK, MOSTRAR_PRODUCTO_POR_NOMBRE_FABRICANTE_KO,
    
    // PROVEEDOR
    REGISTRAR_PROVEEDOR, REGISTRAR_PROVEEDOR_OK, REGISTRAR_PROVEEDOR_KO,
    MODIFICAR_PROVEEDOR, MODIFICAR_PROVEEDOR_OK, MODIFICAR_PROVEEDOR_KO,
    BORRAR_PROVEEDOR, BORRAR_PROVEEDOR_OK, BORRAR_PROVEEDOR_KO,
    LISTAR_PROVEEDORES, LISTAR_PROVEEDORES_OK, LISTAR_PROVEEDORES_KO,
    BUSCAR_PROVEEDOR, BUSCAR_PROVEEDOR_OK, BUSCAR_PROVEEDOR_KO,
    
    // FACTURA TIENDA
    ABRIR_FACTURA,
    AÑADIR_PRODUCTO, AÑADIR_PRODUCTO_OK, AÑADIR_PRODUCTO_KO,
    BUSCAR_FACTURA_POR_ID, BUSCAR_FACTURA_POR_ID_OK, BUSCAR_FACTURA_POR_ID_KO,
    CERRAR_FACTURA, CERRAR_FACTURA_OK, CERRAR_FACTURA_KO,
    DEVOLVER_PRODUCTO, DEVOLVER_PRODUCTO_OK, DEVOLVER_PRODUCTO_KO,
    MOSTRAR_LISTA_FACTURAS, MOSTRAR_LISTA_FACTURAS_OK, MOSTRAR_LISTA_FACTURAS_KO,
    QUITAR_PRODUCTO, QUITAR_PRODUCTO_OK, QUITAR_PRODUCTO_KO,
    LEER_POR_ID_CLIENTE, LEER_POR_ID_CLIENTE_OK, LEER_POR_ID_CLIENTE_KO,
    LEER_POR_ID_DESCUENTO, LEER_POR_ID_DESCUENTO_OK, LEER_POR_ID_DESCUENTO_KO,
    MOSTRAR_PRODUCTO_MAS_COMPRADO, MOSTRAR_PRODUCTO_MAS_COMPRADO_OK, MOSTRAR_PRODUCTO_MAS_COMPRADO_KO,
    MOSTRAR_FACTURA_CON_MAYOR_PORCENTAJE_DESCUENTO, MOSTRAR_FACTURA_CON_MAYOR_PORCENTAJE_DESCUENTO_OK, MOSTRAR_FACTURA_CON_MAYOR_PORCENTAJE_DESCUENTO_KO
    
}
